### ISSUE TITLE
Make textbox fontsize follow user pref

### ISSUE THREAD

**Issue by LettError** [frankrolf/showDist#5]
So we can embiggen the information.

**Comment by frankrolf** [comment]
not a bad idea – I just noticed that some of the info was overflowing the static text box (it seems default TextBox text got slightly bigger in RF?).

Any pointers on how to make the text box size dynamic, @typemytype?

**Comment by typemytype** [comment]
I guess you can call `self.showDist.getNSTextField().sizeToFit()` after you have set text into the vanilla TextBox

https://developer.apple.com/documentation/appkit/nscontrol/1428877-sizetofit?language=objc

**Comment by typemytype** [comment]
that `sizeToFit()` is maybe a nice method to wrap into more vanilla objects (@typesupply)
